"""Пакет jobs."""

from avito.jobs.domain import Application, JobDictionary, JobWebhook, Resume, Vacancy
from avito.jobs.enums import ApplicationStatus, JobActionStatus, VacancyStatus
from avito.jobs.models import (
    ApplicationActionRequest,
    ApplicationIdsQuery,
    ApplicationIdsRequest,
    ApplicationIdsResult,
    ApplicationsResult,
    ApplicationStatesResult,
    ApplicationViewedItem,
    ApplicationViewedRequest,
    JobActionResult,
    JobDictionariesResult,
    JobDictionaryValuesResult,
    JobWebhookInfo,
    JobWebhooksResult,
    JobWebhookUpdateRequest,
    ResumeContactInfo,
    ResumeInfo,
    ResumeSearchQuery,
    ResumesResult,
    VacanciesQuery,
    VacanciesResult,
    VacancyArchiveRequest,
    VacancyAutoRenewalRequest,
    VacancyCreateRequest,
    VacancyIdsRequest,
    VacancyInfo,
    VacancyProlongateRequest,
    VacancyStatusesResult,
    VacancyUpdateRequest,
)

__all__ = (
    "Application",
    "ApplicationActionRequest",
    "ApplicationIdsResult",
    "ApplicationIdsQuery",
    "ApplicationIdsRequest",
    "ApplicationsResult",
    "ApplicationStatus",
    "ApplicationStatesResult",
    "ApplicationViewedItem",
    "ApplicationViewedRequest",
    "JobActionResult",
    "JobActionStatus",
    "JobDictionariesResult",
    "JobDictionary",
    "JobDictionaryValuesResult",
    "JobWebhook",
    "JobWebhookInfo",
    "JobWebhookUpdateRequest",
    "JobWebhooksResult",
    "Resume",
    "ResumeContactInfo",
    "ResumeInfo",
    "ResumeSearchQuery",
    "ResumesResult",
    "VacanciesResult",
    "Vacancy",
    "VacancyArchiveRequest",
    "VacancyAutoRenewalRequest",
    "VacancyCreateRequest",
    "VacancyInfo",
    "VacancyIdsRequest",
    "VacancyProlongateRequest",
    "VacancyStatusesResult",
    "VacanciesQuery",
    "VacancyUpdateRequest",
    "VacancyStatus",
)
